### ISSUE TITLE
More Apple numbers available

### ISSUE THREAD

**Issue by sashavor** [Boavizta/environmental-footprint-data#49]
I think you are missing some values for Apple products, there are some in this report:
https://www.apple.com/environment/pdf/products/desktops/Mac_Pro_PER_Dec2019.pdf

3.5GHz (8-core) processor, Radeon Pro 580X, 32GB memory, and 256GB storage
2765 kg CO2e
2.5GHz (28-core) processor, dual Radeon Pro Vega II Duo with Infinity Fabric Link,
1.5TB memory, Afterburner card, and 4TB storage
6994 kg CO2e

Amazing work!

**Comment by AirLoren** [comment]
Thanks for your submission.
I just added the first one as it is the only one evaluated using a life cycle assessment methodology in accordance with ISO
14040 and 14044 standards
I think percentages (use, manufacturing, transport...) are not the same for the second one.

**Comment by sashavor** [comment]
Great, thanks!
