### ISSUE TITLE
Id to follow for each products

### ISSUE THREAD

**Issue by mfoukette** [Boavizta/environmental-footprint-data#57]
For the csv, it would be great to add an Id column to be able to track changes in any other column.

**Comment by ggael** [comment]
Adding MD5 hash is what I did too on ecodiag's side. This will also ease
comparing the two DB.

**Comment by AirLoren** [comment]
I added MD5 hash on existing spiders.
We will wait for the end of the merge with ECODIAG (@ggael work ongoing) to rebuild whole database with hashes.
