### ISSUE TITLE
Merge Boavizta and Ecodiag parsers

### ISSUE THREAD

**Issue by AirLoren** [Boavizta/environmental-footprint-data#59]
Ecodiag collects data with similar parsers as Boavizta :
https://gitlab.inria.fr/guenneba/ecodiag-data/-/tree/main/pyscripts

Boavizta parsers could be improved at least by using Ecodiag reverse_piechart code to improve all parsers using OCR.

Then Boavizta and Ecodiag parser results could be compared to identify other improvements.

**Comment by ggael** [comment]
For the record, I've already started to integrate the OCR+piechart analyser stuff to the Dell, Lenovo, and HP parsers. A PR should come soon.

**Comment by AirLoren** [comment]
Thanks @ggael for the merge.
