### ISSUE TITLE
🙏 Please use comma for boavizta-data-fr.csv (instead of semicolons)

### ISSUE THREAD

**Issue by adriens** [Boavizta/environmental-footprint-data#84]
# ❔ Context

Actually, the separator used is `;` while using `,` on [GitHub gives a very nice preview](https://github.blog/2013-08-22-see-your-csvs/).
It is done this way on [`boavizta-data-us.csv`](https://github.com/Boavizta/environmental-footprint-data/blob/main/boavizta-data-us.csv) : 

![image](https://user-images.githubusercontent.com/5235127/209738237-4aea321d-33b4-43e5-b509-04f08a7711ac.png)

# 🙏 Action

Please use `,` on [boavizta-data-fr.csv](https://github.com/Boavizta/environmental-footprint-data/blob/main/boavizta-data-fr.csv)

**Comment by anthonygraignic** [comment]
Hey,

The comma `,` is used for describing floating numbers in French e.g. 3,14 for Pi, so it cannot be used as a column separator in CSV files. Hence the dedicated file suffixed with `-fr` and the `;` separator.

`boavizta-data-fr.csv` is a "French CSV" version of the data (not a translated one) to be easily used with Excel or other related tools. So I would advise to only use the `boavizta-data-us.csv` if you want the nice preview (the data are the same) and process data.

See related section in README ;) https://github.com/Boavizta/environmental-footprint-data#data-sets

**Comment by adriens** [comment]
> to be easily used with Excel or other related tools. 

Ok, makes sense :+1: 

Thanks a lot for your feedback.
